language: java
jdk:
 - oraclejdk8
env:
 global:
- COMMIT=${TRAVIS_COMMIT::8}


before_install: 
 - cd services/product-catalog
 - chmod +x mvnw

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=caltuntas/product-catalog-service
  - export TAG=latest
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
