language: java
jdk:
 - oraclejdk8

before_install: 
 - cd services/product-catalog
 - chmod +x mvnw

after_success:
   - docker login -u $DOCKER_USER -p $DOCKER_PASS
   - docker build -t caltuntas/product-catalog-service .
   - docker push caltuntas/product-catalog-service

