sudo: required
dist: trusty
group: deprecated-2017Q4

matrix:
  include:
  - language: java
    jdk: oraclejdk8

    before_install:
      - cd services/product-catalog
      - chmod +x mvnw

    after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker build -t caltuntas/product-catalog-service .
      - docker push caltuntas/product-catalog-service
      - docker login -u _ -p "$HEROKU_KEY"  registry.heroku.com
      - docker tag caltuntas/product-catalog-service:latest registry.heroku.com/product-catalog-service/web
      - docker push registry.heroku.com/product-catalog-service/web

  - language: node_js
    node_js:
      - node

    before_install:
      - sed -i 's|$LOCAL_BACKEND|$BACKEND_URL|' ui/product-catalog/src/environments/environment.ts
      - cat ui/product-catalog/src/environments/environment.ts
      - cd ui/product-catalog
      - npm install

    script:
      - npm run build

    after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker build -t caltuntas/product-catalog-ui .
      - docker push caltuntas/product-catalog-ui
      - docker login -u _ -p "$HEROKU_KEY"  registry.heroku.com
      - docker tag caltuntas/product-catalog-ui:latest registry.heroku.com/product-catalog-ui/web
      - docker push registry.heroku.com/product-catalog-ui/web

