version: '2.2'
services:
  hola:
    build:
      context: ./
      dockerfile: Dockerfile-build
    image: product-catalog
    ports:
      - 8080
    networks:
      - network1
    scale: 3

networks:
  network1:
